export const transactionData = [
  {
    id: "TXN001",
    transactionId: "TXN001",
    buyerName: "Devon Lane",
    sellerName: "Courtney Henry",
    assetName: "Mona Lisa Replica",
    amountUSD: "4886",
    amountETH: "1.9544",
    tokensBrought: "10",
    paymentStatus: "Successful",
    paymentMethod: "Stripe",
    transactionDate: "07-01-2025",
    payoutStatus: "Paid",
    refundStatus: "Not refunded",
    key: 1,
  },
  {
    id: "TXN002",
    transactionId: "TXN002",
    buyerName: "Jacob Jones",
    sellerName: "Theresa Webb",
    assetName: "Oil Painting",
    amountUSD: "1053",
    amountETH: "0.4212",
    tokensBrought: "20",
    paymentStatus: "Pending",
    paymentMethod: "Wallet",
    transactionDate: "07-01-2025",
    payoutStatus: "Pending",
    refundStatus: "Not refunded",
    key: 2,
  },
  {
    id: "TXN003",
    transactionId: "TXN003",
    buyerName: "Theresa Webb",
    sellerName: "Savannah Nguyen",
    assetName: "Vintage Rolex Submariner",
    amountUSD: "2153",
    amountETH: "0.8612",
    tokensBrought: "30",
    paymentStatus: "Failed",
    paymentMethod: "Stripe",
    transactionDate: "07-01-2025",
    payoutStatus: "Failed",
    refundStatus: "Not refunded",
    key: 3,
  },
  {
    id: "TXN004",
    transactionId: "TXN004",
    buyerName: "Jane Cooper",
    sellerName: "Dianne Russell",
    assetName: "Signed Michael Jordan Jersey",
    amountUSD: "1374",
    amountETH: "0.5496",
    tokensBrought: "10",
    paymentStatus: "Successful",
    paymentMethod: "Wallet",
    transactionDate: "07-01-2025",
    payoutStatus: "Paid",
    refundStatus: "Not refunded",
    key: 4,
  },
  {
    id: "TXN005",
    transactionId: "TXN005",
    buyerName: "Darrell Steward",
    sellerName: "Annette Black",
    assetName: "Picasso's Sketch Print",
    amountUSD: "4886",
    amountETH: "1.9544",
    tokensBrought: "20",
    paymentStatus: "Pending",
    paymentMethod: "Stripe",
    transactionDate: "07-01-2025",
    payoutStatus: "Pending",
    refundStatus: "Not refunded",
    key: 5,
  },
  {
    id: "TXN006",
    transactionId: "TXN006",
    buyerName: "Cody Fisher",
    sellerName: "Guy Hawkins",
    assetName: "Rare Pokémon Holographic Card",
    amountUSD: "1053",
    amountETH: "0.4212",
    tokensBrought: "30",
    paymentStatus: "Failed",
    paymentMethod: "Wallet",
    transactionDate: "07-01-2025",
    payoutStatus: "Failed",
    refundStatus: "Not refunded",
    key: 6,
  },
  {
    id: "TXN007",
    transactionId: "TXN007",
    buyerName: "Albert Flores",
    sellerName: "Robert Fox",
    assetName: "Mona Lisa Replica",
    amountUSD: "2153",
    amountETH: "0.8612",
    tokensBrought: "10",
    paymentStatus: "Successful",
    paymentMethod: "Stripe",
    transactionDate: "07-01-2025",
    payoutStatus: "Successful",
    refundStatus: "Not refunded",
    key: 7,
  },
  {
    id: "TXN008",
    transactionId: "TXN008",
    buyerName: "Brooklyn Simmons",
    sellerName: "Esther Howard",
    assetName: "Vintage Rolex Submariner",
    amountUSD: "1374",
    amountETH: "0.5496",
    tokensBrought: "20",
    paymentStatus: "Pending",
    paymentMethod: "Wallet",
    transactionDate: "07-01-2025",
    payoutStatus: "Pending",
    refundStatus: "Not refunded",
    key: 8,
  },
  {
    id: "TXN009",
    transactionId: "TXN009",
    buyerName: "Albert Flores",
    sellerName: "Robert Fox",
    assetName: "Mona Lisa Replica",
    amountUSD: "2153",
    amountETH: "0.8612",
    tokensBrought: "10",
    paymentStatus: "Successful",
    paymentMethod: "Stripe",
    transactionDate: "07-01-2025",
    payoutStatus: "Successful",
    refundStatus: "Not refunded",
    key: 9,
  },
];
